<script setup lang="ts">
import { Badge, Button, Dialog, LoadingIndicator } from 'frappe-ui'
import { Newspaper, Package, User, Calendar, Zap, Truck, FileText } from 'lucide-vue-next'
import { computed } from 'vue'

const props = defineProps<{
  modelValue: boolean
  orderDetails: any
  processingId: string
  formatCurrency: (amount: number, currency?: string) => string
  getStatusTheme: (status: string) => string
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void
  (e: 'order-action', id: string, action: string): void
}>()

const open = computed({
  get: () => props.modelValue,
  set: (v) => emit('update:modelValue', v)
})
</script>

<template>
  <Dialog v-model="open" :options="{ size: '4xl' }">
    <template #body-title>
      <div class="flex items-center justify-between w-full pr-6 sm:pr-8 gap-2 flex-wrap">
        <div class="flex items-center gap-2 sm:gap-3 min-w-0">
          <div :class="[
            'h-8 w-8 sm:h-10 sm:w-10 rounded-full flex items-center justify-center flex-shrink-0',
            orderDetails?.custom_subscription_refereance ? 'bg-blue-50 text-blue-600' : 'bg-gray-50 text-gray-600'
          ]">
            <Newspaper v-if="orderDetails?.custom_subscription_refereance" class="w-4 h-4 sm:w-5 sm:h-5" />
            <Package v-else class="w-4 h-4 sm:w-5 sm:h-5" />
          </div>
          <div class="min-w-0">
            <h3 class="text-base sm:text-xl font-black leading-none">Order Details</h3>
            <p class="text-xs sm:text-sm text-gray-500 font-mono mt-1 truncate">
              {{ orderDetails?.name }}
            </p>
          </div>
        </div>
        <div class="flex items-center gap-1.5 sm:gap-2 flex-wrap">
          <span
            v-if="orderDetails?.custom_subscription_refereance"
            class="inline-flex items-center gap-1 bg-blue-100 text-blue-700 text-[10px] sm:text-xs font-bold px-2 sm:px-3 py-1 rounded-full truncate max-w-[140px] sm:max-w-none"
          >
            <Newspaper class="w-3 h-3 flex-shrink-0" />
            <span class="truncate">{{ orderDetails.custom_subscription_refereance }}</span>
          </span>
          <Badge
            v-if="orderDetails"
            :theme="(getStatusTheme(orderDetails.status) as any)"
            size="lg"
            :label="orderDetails.status"
          />
        </div>
      </div>
    </template>

    <template #body-content>
      <!-- Loading -->
      <div v-if="!orderDetails" class="flex flex-col items-center justify-center h-48 sm:h-80">
        <LoadingIndicator class="w-8 h-8 sm:w-10 sm:h-10 text-blue-500" />
      </div>

      <div v-else class="py-4 sm:py-6 space-y-5 sm:space-y-8">

        <!-- Sub order info banner -->
        <div
          v-if="orderDetails.custom_subscription_refereance && orderDetails.docstatus === 1"
          class="flex items-start gap-2 sm:gap-3 bg-blue-50 border border-blue-200 rounded-xl sm:rounded-2xl p-3 sm:p-4"
        >
          <Zap class="w-4 h-4 sm:w-5 sm:h-5 text-blue-500 mt-0.5 flex-shrink-0" />
          <p class="text-[10px] sm:text-xs text-blue-700">
            <span class="font-bold">Daily Subscription Order.</span>
            Auto-generated by cron. Delivery note created automatically.
            Only invoice needed manually.
          </p>
        </div>

        <!-- Meta cards: stack on mobile, 3 cols on md+ -->
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-5">
          <div class="bg-gray-50 p-3 sm:p-5 rounded-xl sm:rounded-2xl border border-gray-100 flex items-start gap-2 sm:gap-3">
            <div class="bg-white p-1.5 sm:p-2 rounded-lg shadow-sm text-gray-500 flex-shrink-0">
              <User class="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            </div>
            <div class="min-w-0">
              <p class="text-[10px] sm:text-[11px] font-bold text-gray-400 uppercase tracking-widest mb-1">Customer</p>
              <p class="font-bold text-sm sm:text-base truncate">{{ orderDetails.customer_name }}</p>
            </div>
          </div>
          <div class="bg-gray-50 p-3 sm:p-5 rounded-xl sm:rounded-2xl border border-gray-100 flex items-start gap-2 sm:gap-3">
            <div class="bg-white p-1.5 sm:p-2 rounded-lg shadow-sm text-gray-500 flex-shrink-0">
              <Calendar class="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            </div>
            <div>
              <p class="text-[10px] sm:text-[11px] font-bold text-gray-400 uppercase tracking-widest mb-1">Date</p>
              <p class="font-bold text-sm sm:text-base">{{ orderDetails.transaction_date }}</p>
            </div>
          </div>
          <div class="bg-blue-600 p-3 sm:p-5 rounded-xl sm:rounded-2xl text-white">
            <p class="text-[10px] sm:text-[11px] font-bold text-blue-200 uppercase tracking-widest mb-1">Grand Total</p>
            <p class="font-black text-xl sm:text-2xl">
              {{ formatCurrency(orderDetails.grand_total, orderDetails.currency) }}
            </p>
          </div>
        </div>

        <!-- Items table - horizontally scrollable on mobile -->
        <div class="border border-gray-200 rounded-xl overflow-hidden">
          <div class="overflow-x-auto">
            <table class="w-full text-xs sm:text-sm min-w-[400px]">
              <thead class="bg-gray-50 text-[9px] sm:text-[10px] uppercase font-bold text-gray-500">
                <tr>
                  <th class="px-3 sm:px-5 py-3 sm:py-4 text-left">Item</th>
                  <th class="px-3 sm:px-5 py-3 sm:py-4 text-right">Qty</th>
                  <th class="px-3 sm:px-5 py-3 sm:py-4 text-right">Rate</th>
                  <th class="px-3 sm:px-5 py-3 sm:py-4 text-right">Amount</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-100">
                <tr v-for="item in orderDetails.items" :key="item.name">
                  <td class="px-3 sm:px-5 py-3 sm:py-4 font-bold text-gray-900">{{ item.item_name }}</td>
                  <td class="px-3 sm:px-5 py-3 sm:py-4 text-right tabular-nums">{{ item.qty }}</td>
                  <td class="px-3 sm:px-5 py-3 sm:py-4 text-right tabular-nums">
                    {{ formatCurrency(item.rate, orderDetails.currency) }}
                  </td>
                  <td class="px-3 sm:px-5 py-3 sm:py-4 text-right font-bold tabular-nums">
                    {{ formatCurrency(item.amount, orderDetails.currency) }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Action buttons - stack on mobile -->
        <div class="flex flex-col xs:flex-row justify-end gap-2 sm:gap-3 pt-4 sm:pt-6 border-t border-gray-100">
          <Button
            v-if="orderDetails.docstatus === 0"
            variant="solid" theme="blue" size="xl"
            :loading="processingId === orderDetails.name"
            class="w-full xs:w-auto"
            @click="emit('order-action', orderDetails.name, 'accept')"
          >Accept Order</Button>

          <Button
            v-if="orderDetails.docstatus === 1 && orderDetails.per_delivered < 100 && !orderDetails.custom_subscription_refereance"
            variant="solid" theme="gray" size="xl"
            :loading="processingId === orderDetails.name"
            class="w-full xs:w-auto"
            @click="emit('order-action', orderDetails.name, 'deliver')"
          >
            <template #prefix><Truck class="w-4 h-4" /></template>
            Generate Delivery Note
          </Button>

          <Button
            v-if="orderDetails.per_delivered >= 100 && orderDetails.per_billed < 100"
            variant="solid" theme="gray" size="xl"
            :loading="processingId === orderDetails.name"
            class="w-full xs:w-auto"
            @click="emit('order-action', orderDetails.name, 'invoice')"
          >
            <template #prefix><FileText class="w-4 h-4" /></template>
            Generate Invoice
          </Button>
        </div>
      </div>
    </template>
  </Dialog>
</template>